spring:
  application:
    name: ai-shopping-mall-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.12.61.26:3534/ai_shopping_mall?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:trade-manage}
    password: ${SPRING_DATASOURCE_PASSWORD:QAZ123wsx!!}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8080

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
  seaweedfs:
    server:
      addr: ${APP_SEAWEEDFS_SERVER_ADDR:http://10.12.19.126:9333}
