spring:
  application:
    name: ai-shopping-mall-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.12.61.26:3534/ai_shopping_mall?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:trade-manage}
    password: ${SPRING_DATASOURCE_PASSWORD:QAZ123wsx!!}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

server:
  port: 8080

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
  seaweedfs:
    server:
      addr: ${APP_SEAWEEDFS_SERVER_ADDR:http://10.12.19.126:9333}

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${LOG_PATH:logs}
